apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-caller
  labels:
    app: hello-caller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-caller
  template:
    metadata:
      labels:
        app: hello-caller
    spec:
      containers:
      - name: hello-caller
        image: ghcr.io/yourusername/hello-caller:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
