name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/hello-caller
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: ./mvnw clean package -DskipTests
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=sha,format=short
          type=ref,event=branch
          latest
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    
    - name: Update Kubernetes manifests
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        cd k8s
        sed -i "s|image: .*|image: ${{ env.IMAGE_NAME }}:sha-${{ github.sha }}|g" deployment.yaml
        git add .
        git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
        git push

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Trigger ArgoCD sync
      run: |
        # You can use ArgoCD API to trigger a sync
        # curl -sSL -k -X POST \
        #   -H "Authorization: Bearer ${{ secrets.ARGOCD_TOKEN }}" \
        #   ${{ secrets.ARGOCD_SERVER }}/api/v1/applications/hello-caller/sync
        echo "ArgoCD will automatically detect changes and sync"
